"""core schema

Revision ID: ec262437a8c3
Revises: 0d5cd2cce021
Create Date: 2026-09-24 12:25:54.463551

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ec262437a8c3'
down_revision: str | None = '0d5cd2cce021'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints_monthly',
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('model_year', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=255), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('crash', sa.Integer(), nullable=True),
    sa.Column('fire', sa.Integer(), nullable=True),
    sa.Column('injured', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('make', 'model', 'model_year', 'component', 'month')
    )
    op.create_table('intent_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('utterance', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_examples_intent'), 'intent_examples', ['intent'], unique=False)
    op.create_table('kb_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('kb_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_path')
    )
    op.create_table('llm_usage_daily',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('day', 'provider')
    )
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('bay_count', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('mon_open', sa.String(length=8), nullable=True),
    sa.Column('mon_close', sa.String(length=8), nullable=True),
    sa.Column('tue_open', sa.String(length=8), nullable=True),
    sa.Column('tue_close', sa.String(length=8), nullable=True),
    sa.Column('wed_open', sa.String(length=8), nullable=True),
    sa.Column('wed_close', sa.String(length=8), nullable=True),
    sa.Column('thu_open', sa.String(length=8), nullable=True),
    sa.Column('thu_close', sa.String(length=8), nullable=True),
    sa.Column('fri_open', sa.String(length=8), nullable=True),
    sa.Column('fri_close', sa.String(length=8), nullable=True),
    sa.Column('sat_open', sa.String(length=8), nullable=True),
    sa.Column('sat_close', sa.String(length=8), nullable=True),
    sa.Column('sun_open', sa.String(length=8), nullable=True),
    sa.Column('sun_close', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('nhtsa_cache',
    sa.Column('request_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('request_key')
    )
    op.create_table('parts',
    sa.Column('part_no', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('list_price', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('part_no')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('recall_campaigns',
    sa.Column('campaign_number', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('model_year', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('consequence', sa.String(), nullable=True),
    sa.Column('remedy', sa.String(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('campaign_number', 'make', 'model', 'model_year')
    )
    op.create_table('recall_summaries',
    sa.Column('campaign_number', sa.String(length=20), nullable=False),
    sa.Column('short_summary', sa.String(), nullable=True),
    sa.Column('voice_summary', sa.String(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('campaign_number')
    )
    op.create_table('response_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_catalog',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('labor_hours_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('labor_hours_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('parts_cost_min', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('parts_cost_max', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('bay_type', sa.String(length=30), nullable=True),
    sa.Column('skill_level', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('vehicle_catalog',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('nhtsa_model_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('year', 'make', 'model')
    )
    op.create_table('bays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('bay_number', sa.Integer(), nullable=False),
    sa.Column('bay_type', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bays_location_id'), 'bays', ['location_id'], unique=False)
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('email_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('preferred_location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['preferred_location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index('ix_customers_email_hash', 'customers', ['email_hash'], unique=False)
    op.create_index('ix_customers_phone_hash', 'customers', ['phone_hash'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('technicians',
    sa.Column('technician_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('skill_level', sa.String(length=5), nullable=True),
    sa.Column('certifications', sa.String(length=500), nullable=True),
    sa.Column('shift_pattern', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('efficiency_base', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('technician_id')
    )
    op.create_index(op.f('ix_technicians_location_id'), 'technicians', ['location_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('mfa_secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('shift_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('technician_id', sa.String(length=20), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=True),
    sa.Column('end_time', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.technician_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_templates_technician_id'), 'shift_templates', ['technician_id'], unique=False)
    op.create_table('technician_skills',
    sa.Column('technician_id', sa.String(length=20), nullable=False),
    sa.Column('skill_code', sa.String(length=50), nullable=False),
    sa.Column('proficiency', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.technician_id'], ),
    sa.PrimaryKeyConstraint('technician_id', 'skill_code')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('nhtsa_model_name', sa.String(length=100), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_index(op.f('ix_vehicles_customer_id'), 'vehicles', ['customer_id'], unique=False)
    op.create_table('appointments',
    sa.Column('appointment_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('vehicle_id', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.String(length=20), nullable=True),
    sa.Column('bay_number', sa.Integer(), nullable=True),
    sa.Column('service_code', sa.String(length=30), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('channel_created', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['service_code'], ['service_catalog.code'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.technician_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index(op.f('ix_appointments_customer_id'), 'appointments', ['customer_id'], unique=False)
    op.create_index('ix_appointments_location_start', 'appointments', ['location_id', 'scheduled_start'], unique=False)
    op.create_index(op.f('ix_appointments_vehicle_id'), 'appointments', ['vehicle_id'], unique=False)
    op.create_table('conversations',
    sa.Column('conversation_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contained', sa.Boolean(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=True),
    sa.Column('resulting_appointment_id', sa.String(length=20), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['resulting_appointment_id'], ['appointments.appointment_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('repair_orders',
    sa.Column('ro_id', sa.String(length=20), nullable=False),
    sa.Column('appointment_id', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('vehicle_id', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.String(length=20), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pay_type', sa.String(length=20), nullable=True),
    sa.Column('recall_campaign_number', sa.String(length=20), nullable=True),
    sa.Column('labor_rate', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('labor_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('labor_amount', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('parts_amount', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.technician_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('ro_id')
    )
    op.create_index(op.f('ix_repair_orders_appointment_id'), 'repair_orders', ['appointment_id'], unique=False)
    op.create_index('ix_repair_orders_closed_at', 'repair_orders', ['closed_at'], unique=False)
    op.create_index(op.f('ix_repair_orders_customer_id'), 'repair_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_repair_orders_vehicle_id'), 'repair_orders', ['vehicle_id'], unique=False)
    op.create_table('csat_surveys',
    sa.Column('survey_id', sa.String(length=20), nullable=False),
    sa.Column('ro_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('wait_time_minutes', sa.Integer(), nullable=True),
    sa.Column('promise_time_minutes', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['ro_id'], ['repair_orders.ro_id'], ),
    sa.PrimaryKeyConstraint('survey_id')
    )
    op.create_index(op.f('ix_csat_surveys_ro_id'), 'csat_surveys', ['ro_id'], unique=False)
    op.create_table('escalations',
    sa.Column('escalation_id', sa.String(length=20), nullable=False),
    sa.Column('conversation_id', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('escalation_id')
    )
    op.create_index(op.f('ix_escalations_conversation_id'), 'escalations', ['conversation_id'], unique=False)
    op.create_index('ix_escalations_open', 'escalations', ['status'], unique=False, postgresql_where="status = 'open'")
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=20), nullable=False),
    sa.Column('conversation_id', sa.String(length=20), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(length=10), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('slots', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=20), nullable=False),
    sa.Column('ro_id', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ro_id'], ['repair_orders.ro_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_ro_id'), 'payments', ['ro_id'], unique=False)
    op.create_table('ro_line_items',
    sa.Column('line_id', sa.String(length=20), nullable=False),
    sa.Column('ro_id', sa.String(length=20), nullable=False),
    sa.Column('service_code', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('labor_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('labor_amount', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('parts_amount', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('line_amount', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('is_upsell', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ro_id'], ['repair_orders.ro_id'], ),
    sa.PrimaryKeyConstraint('line_id')
    )
    op.create_index(op.f('ix_ro_line_items_ro_id'), 'ro_line_items', ['ro_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ro_line_items_ro_id'), table_name='ro_line_items')
    op.drop_table('ro_line_items')
    op.drop_index(op.f('ix_payments_ro_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_escalations_open', table_name='escalations', postgresql_where="status = 'open'")
    op.drop_index(op.f('ix_escalations_conversation_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_csat_surveys_ro_id'), table_name='csat_surveys')
    op.drop_table('csat_surveys')
    op.drop_index(op.f('ix_repair_orders_vehicle_id'), table_name='repair_orders')
    op.drop_index(op.f('ix_repair_orders_customer_id'), table_name='repair_orders')
    op.drop_index('ix_repair_orders_closed_at', table_name='repair_orders')
    op.drop_index(op.f('ix_repair_orders_appointment_id'), table_name='repair_orders')
    op.drop_table('repair_orders')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_appointments_vehicle_id'), table_name='appointments')
    op.drop_index('ix_appointments_location_start', table_name='appointments')
    op.drop_index(op.f('ix_appointments_customer_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_vehicles_customer_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('user_roles')
    op.drop_table('technician_skills')
    op.drop_index(op.f('ix_shift_templates_technician_id'), table_name='shift_templates')
    op.drop_table('shift_templates')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('mfa_secrets')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_technicians_location_id'), table_name='technicians')
    op.drop_table('technicians')
    op.drop_table('role_permissions')
    op.drop_index('ix_customers_phone_hash', table_name='customers')
    op.drop_index('ix_customers_email_hash', table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_bays_location_id'), table_name='bays')
    op.drop_table('bays')
    op.drop_table('vehicle_catalog')
    op.drop_table('service_catalog')
    op.drop_table('roles')
    op.drop_table('response_cache')
    op.drop_table('recall_summaries')
    op.drop_table('recall_campaigns')
    op.drop_table('permissions')
    op.drop_table('parts')
    op.drop_table('nhtsa_cache')
    op.drop_table('locations')
    op.drop_table('llm_usage_daily')
    op.drop_table('kb_documents')
    op.drop_table('kb_chunks')
    op.drop_index(op.f('ix_intent_examples_intent'), table_name='intent_examples')
    op.drop_table('intent_examples')
    op.drop_table('complaints_monthly')
    # ### end Alembic commands ###
